services:
  smshog:
    # image: zauberware/smshog:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:80"
    environment:
      - NODE_ENV=production 
    env_file:
      - .env
    volumes:
      - ./data:/data:rw
      
